# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ZephyrCloudIO.ZeHarness
PackageVersion: 0.5.1
InstallerType: zip
NestedInstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: https://downloads.ze.dev/releases/v0.5.1/ze-harness-v0.5.1-x86_64-pc-windows-msvc.zip
    InstallerSha256: 67B8F792C79C322FEAF5839F9D5D41BC9990CBA65EA44431C9C0D4DDEECE08F6
    NestedInstallerFiles:
      - RelativeFilePath: ze-harness.exe
        PortableCommandAlias: ze-harness
ManifestType: installer
ManifestVersion: 1.12.0
